//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class AccesoDenegado
    {
        /// <summary>Control litNivel.</summary>
        protected global::System.Web.UI.WebControls.Literal litNivel;
    }
}
