//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class CambiarClave
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtActual.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtActual;

        /// <summary>Control txtNueva.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNueva;

        /// <summary>Control txtRepetir.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtRepetir;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
