//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Clientes
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control hdnVieneDeVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeVehiculo;

        /// <summary>Control hdnVhIdVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhIdVehiculo;

        /// <summary>Control hdnVhActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhActivo;

        /// <summary>Control hdnVhIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhIdCliente;

        /// <summary>Control hdnVhPatente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhPatente;

        /// <summary>Control hdnVhMarca.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhMarca;

        /// <summary>Control hdnVhModelo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhModelo;

        /// <summary>Control hdnVhAnio.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhAnio;

        /// <summary>Control hdnVhTipoCombustible.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhTipoCombustible;

        /// <summary>Control pnlVieneDeVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeVehiculo;

        /// <summary>Control btnVolverAVehiculos.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAVehiculos;

        /// <summary>Control hdnVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeOrden;

        /// <summary>Control hdnOrKilometraje.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrKilometraje;

        /// <summary>Control hdnOrObservaciones.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrObservaciones;

        /// <summary>Control hdnOrIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrIdTurno;

        /// <summary>Control pnlVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeOrden;

        /// <summary>Control btnVolverAOrdenes.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAOrdenes;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control chkIncluirInactivos.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIncluirInactivos;

        /// <summary>Control gvClientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvClientes;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control txtApellido.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>Control txtDni.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDni;

        /// <summary>Control txtTelefono.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        /// <summary>Control txtEmail.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>Control txtDireccion.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;
    }
}
