//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Clientes
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control hdnVieneDeVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeVehiculo;

        /// <summary>Control hdnVhIdVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhIdVehiculo;

        /// <summary>Control hdnVhActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhActivo;

        /// <summary>Control hdnVhIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhIdCliente;

        /// <summary>Control hdnVhPatente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhPatente;

        /// <summary>Control hdnVhMarca.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhMarca;

        /// <summary>Control hdnVhModelo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhModelo;

        /// <summary>Control hdnVhAnio.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhAnio;

        /// <summary>Control hdnVhTipoCombustible.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhTipoCombustible;

        /// <summary>Control hdnVhCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVhCambioDueno;

        /// <summary>Control hdnVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeOrden;

        /// <summary>Control hdnOrKilometraje.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrKilometraje;

        /// <summary>Control hdnOrObservaciones.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrObservaciones;

        /// <summary>Control hdnOrIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrIdTurno;

        /// <summary>Control hdnVieneDeCuentaCorriente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeCuentaCorriente;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvClientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvClientes;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control pnlVieneDeVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeVehiculo;

        /// <summary>Control litVieneDeVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Literal litVieneDeVehiculo;

        /// <summary>Control btnVolverAVehiculos.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAVehiculos;

        /// <summary>Control pnlVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeOrden;

        /// <summary>Control btnVolverAOrdenes.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAOrdenes;

        /// <summary>Control pnlVieneDeCuentaCorriente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeCuentaCorriente;

        /// <summary>Control btnVolverACuentaCorriente.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverACuentaCorriente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control rblTipoCliente.</summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblTipoCliente;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control txtApellido.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>Control txtRazonSocial.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;

        /// <summary>Control ddlTipoDocumento.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoDocumento;

        /// <summary>Control txtNumeroDocumento.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroDocumento;

        /// <summary>Control valNumeroDocumento.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator valNumeroDocumento;

        /// <summary>Control ddlCondicionIva.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCondicionIva;

        /// <summary>Control txtTelefono.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        /// <summary>Control txtEmail.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>Control txtDireccion.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        /// <summary>Control txtCodigoPostal.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCodigoPostal;

        /// <summary>Control txtLocalidad.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLocalidad;

        /// <summary>Control ddlProvincia.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlProvincia;

        /// <summary>Control chkCuentaCorriente.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCuentaCorriente;

        /// <summary>Control litCuentaCorrienteBloqueada.</summary>
        protected global::System.Web.UI.WebControls.Literal litCuentaCorrienteBloqueada;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;

        /// <summary>Control btnReactivar.</summary>
        protected global::System.Web.UI.WebControls.Button btnReactivar;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
