//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Compras
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control chkSoloConSaldo.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkSoloConSaldo;

        /// <summary>Control btnNuevaCompra.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevaCompra;

        /// <summary>Control gvCompras.</summary>
        protected global::System.Web.UI.WebControls.GridView gvCompras;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control upnlCompra.</summary>
        protected global::System.Web.UI.UpdatePanel upnlCompra;

        /// <summary>Control pnlMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensajeFormulario;

        /// <summary>Control litMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensajeFormulario;

        /// <summary>Control hdnIdCompra.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCompra;

        /// <summary>Control pnlAltaCompra.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAltaCompra;

        /// <summary>Control txtProveedor.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtProveedor;

        /// <summary>Control hdnIdProveedor.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdProveedor;

        /// <summary>Control ddlCondicionPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCondicionPago;

        /// <summary>Control pnlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMedioPago;

        /// <summary>Control ddlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMedioPago;

        /// <summary>Control txtImpuestos.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtImpuestos;

        /// <summary>Control pnlAgregarLinea.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAgregarLinea;

        /// <summary>Control ddlInsumo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlInsumo;

        /// <summary>Control txtCantidadLinea.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadLinea;

        /// <summary>Control txtPrecioLinea.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrecioLinea;

        /// <summary>Control btnAgregarLinea.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarLinea;

        /// <summary>Control gvLineasPendientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvLineasPendientes;

        /// <summary>Control pnlCompraExistente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCompraExistente;

        /// <summary>Control litProveedorInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litProveedorInfo;

        /// <summary>Control litFechaInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litFechaInfo;

        /// <summary>Control litCondicionInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litCondicionInfo;

        /// <summary>Control litMedioPagoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litMedioPagoInfo;

        /// <summary>Control litSubtotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSubtotalInfo;

        /// <summary>Control litImpuestosInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litImpuestosInfo;

        /// <summary>Control litTotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalInfo;

        /// <summary>Control litSaldoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSaldoInfo;

        /// <summary>Control gvDetalleCompra.</summary>
        protected global::System.Web.UI.WebControls.GridView gvDetalleCompra;

        /// <summary>Control litBotonCerrar.</summary>
        protected global::System.Web.UI.WebControls.Literal litBotonCerrar;

        /// <summary>Control btnGuardarCompra.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarCompra;
    }
}
