//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Compras
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control chkSoloConSaldo.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkSoloConSaldo;

        /// <summary>Control gvCompras.</summary>
        protected global::System.Web.UI.WebControls.GridView gvCompras;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdCompra.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCompra;

        /// <summary>Control pnlAltaCompra.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAltaCompra;

        /// <summary>Control upnlProveedor.</summary>
        protected global::System.Web.UI.UpdatePanel upnlProveedor;

        /// <summary>Control hdnIdProveedor.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdProveedor;

        /// <summary>Control litProveedorSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litProveedorSeleccionado;

        /// <summary>Control txtBuscarProveedor.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarProveedor;

        /// <summary>Control btnBuscarProveedor.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarProveedor;

        /// <summary>Control pnlResultadosProveedor.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosProveedor;

        /// <summary>Control rptResultadosProveedor.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosProveedor;

        /// <summary>Control ddlCondicionPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCondicionPago;

        /// <summary>Control pnlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMedioPago;

        /// <summary>Control ddlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMedioPago;

        /// <summary>Control txtImpuestos.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtImpuestos;

        /// <summary>Control ddlInsumo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlInsumo;

        /// <summary>Control txtCantidadLinea.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadLinea;

        /// <summary>Control txtPrecioLinea.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrecioLinea;

        /// <summary>Control btnAgregarLinea.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarLinea;

        /// <summary>Control gvLineasPendientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvLineasPendientes;

        /// <summary>Control btnGuardarCompra.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarCompra;

        /// <summary>Control pnlCompraExistente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCompraExistente;

        /// <summary>Control litProveedorInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litProveedorInfo;

        /// <summary>Control litFechaInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litFechaInfo;

        /// <summary>Control litCondicionInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litCondicionInfo;

        /// <summary>Control litMedioPagoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litMedioPagoInfo;

        /// <summary>Control litSubtotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSubtotalInfo;

        /// <summary>Control litImpuestosInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litImpuestosInfo;

        /// <summary>Control litTotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalInfo;

        /// <summary>Control litSaldoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSaldoInfo;

        /// <summary>Control gvDetalleCompra.</summary>
        protected global::System.Web.UI.WebControls.GridView gvDetalleCompra;

        /// <summary>Control btnNuevaCompra.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevaCompra;
    }
}
