//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class CuentaCorrienteClientes
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control gvClientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvClientes;

        /// <summary>Control pnlDetalle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Literal litClienteSeleccionado;

        /// <summary>Control litSaldoActual.</summary>
        protected global::System.Web.UI.WebControls.Literal litSaldoActual;

        /// <summary>Control gvHistorial.</summary>
        protected global::System.Web.UI.WebControls.GridView gvHistorial;

        /// <summary>Control pnlAjuste.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAjuste;

        /// <summary>Control txtMontoAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMontoAjuste;

        /// <summary>Control txtMotivoAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivoAjuste;

        /// <summary>Control btnRegistrarAjuste.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrarAjuste;
    }
}
