//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class CuentaCorrienteClientes
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control gvClientes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvClientes;

        /// <summary>Control pnlDetalle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Literal litClienteSeleccionado;

        /// <summary>Control pnlMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensajeFormulario;

        /// <summary>Control litMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensajeFormulario;

        /// <summary>Control pnlSinCuenta.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinCuenta;

        /// <summary>Control litSaldoActual.</summary>
        protected global::System.Web.UI.WebControls.Literal litSaldoActual;

        /// <summary>Control pnlHistorial.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlHistorial;

        /// <summary>Control gvHistorial.</summary>
        protected global::System.Web.UI.WebControls.GridView gvHistorial;

        /// <summary>Control pnlAjuste.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAjuste;

        /// <summary>Control txtMontoAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMontoAjuste;

        /// <summary>Control txtMotivoAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivoAjuste;

        /// <summary>Control btnRegistrarAjuste.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrarAjuste;

        /// <summary>Control lnkEditarCliente.</summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditarCliente;
    }
}
