//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class DatosComercio
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control txtRazonSocial.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;

        /// <summary>Control txtCuit.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCuit;

        /// <summary>Control txtDomicilio.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDomicilio;

        /// <summary>Control ddlCondicionIva.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCondicionIva;

        /// <summary>Control txtPuntoVenta.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPuntoVenta;

        /// <summary>Control valPuntoVenta.</summary>
        protected global::System.Web.UI.WebControls.RangeValidator valPuntoVenta;

        /// <summary>Control txtIngresosBrutos.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtIngresosBrutos;

        /// <summary>Control txtInicioActividades.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtInicioActividades;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
