//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class _Default
    {
        /// <summary>Control litNombre.</summary>
        protected global::System.Web.UI.WebControls.Literal litNombre;

        /// <summary>Control litNivel.</summary>
        protected global::System.Web.UI.WebControls.Literal litNivel;

        /// <summary>Control litAccesos.</summary>
        protected global::System.Web.UI.WebControls.Literal litAccesos;
    }
}
