//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Insumos
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control chkIncluirInactivos.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIncluirInactivos;

        /// <summary>Control gvInsumos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvInsumos;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdInsumo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdInsumo;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control txtMarca.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarca;

        /// <summary>Control ddlUnidadMedida.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlUnidadMedida;

        /// <summary>Control txtStockMinimo.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtStockMinimo;

        /// <summary>Control txtPrecioVenta.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrecioVenta;

        /// <summary>Control txtStockInicial.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtStockInicial;

        /// <summary>Control litStockActual.</summary>
        protected global::System.Web.UI.WebControls.Label litStockActual;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;

        /// <summary>Control pnlAjusteHistorial.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAjusteHistorial;

        /// <summary>Control txtCantidadAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadAjuste;

        /// <summary>Control txtMotivoAjuste.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivoAjuste;

        /// <summary>Control btnRegistrarAjuste.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrarAjuste;

        /// <summary>Control gvHistorial.</summary>
        protected global::System.Web.UI.WebControls.GridView gvHistorial;
    }
}
