//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class OrdenesDeTrabajo
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvOrdenes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvOrdenes;

        /// <summary>Control litTituloVer.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloVer;

        /// <summary>Control litVerCliente.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerCliente;

        /// <summary>Control litVerVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerVehiculo;

        /// <summary>Control litVerTurno.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerTurno;

        /// <summary>Control litVerFecha.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerFecha;

        /// <summary>Control litVerKilometraje.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerKilometraje;

        /// <summary>Control litVerEstado.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerEstado;

        /// <summary>Control litVerUsuario.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerUsuario;

        /// <summary>Control litVerVenta.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerVenta;

        /// <summary>Control litVerObservaciones.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerObservaciones;

        /// <summary>Control gvVerServicios.</summary>
        protected global::System.Web.UI.WebControls.GridView gvVerServicios;

        /// <summary>Control gvVerInsumos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvVerInsumos;

        /// <summary>Control litVerTotal.</summary>
        protected global::System.Web.UI.WebControls.Literal litVerTotal;

        /// <summary>Control btnEditarDesdeVer.</summary>
        protected global::System.Web.UI.WebControls.Button btnEditarDesdeVer;

        /// <summary>Control hdnIdOrdenVer.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdOrdenVer;

        /// <summary>Control pnlDialogo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDialogo;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control upnlOrden.</summary>
        protected global::System.Web.UI.UpdatePanel upnlOrden;

        /// <summary>Control pnlMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensajeFormulario;

        /// <summary>Control litMensajeFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensajeFormulario;

        /// <summary>Control hdnIdOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdOrden;

        /// <summary>Control pnlSeleccionNueva.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSeleccionNueva;

        /// <summary>Control txtCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control btnNuevoCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoCliente;

        /// <summary>Control ddlVehiculo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVehiculo;

        /// <summary>Control btnNuevoVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoVehiculo;

        /// <summary>Control ddlTurno.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTurno;

        /// <summary>Control pnlSeleccionFija.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSeleccionFija;

        /// <summary>Control litClienteInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litClienteInfo;

        /// <summary>Control litVehiculoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litVehiculoInfo;

        /// <summary>Control litTurnoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litTurnoInfo;

        /// <summary>Control txtKilometraje.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtKilometraje;

        /// <summary>Control pnlEstado.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEstado;

        /// <summary>Control ddlEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>Control litEstadoActual.</summary>
        protected global::System.Web.UI.WebControls.Label litEstadoActual;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control pnlDetalle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        /// <summary>Control pnlAgregarServicio.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAgregarServicio;

        /// <summary>Control ddlServicio.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlServicio;

        /// <summary>Control txtCantidadServicio.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadServicio;

        /// <summary>Control btnAgregarServicio.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarServicio;

        /// <summary>Control gvServicios.</summary>
        protected global::System.Web.UI.WebControls.GridView gvServicios;

        /// <summary>Control pnlAgregarInsumo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAgregarInsumo;

        /// <summary>Control ddlInsumo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlInsumo;

        /// <summary>Control txtCantidadInsumo.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadInsumo;

        /// <summary>Control btnAgregarInsumo.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarInsumo;

        /// <summary>Control gvInsumosOrden.</summary>
        protected global::System.Web.UI.WebControls.GridView gvInsumosOrden;

        /// <summary>Control litTotalOrden.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalOrden;

        /// <summary>Control litConfirmarCierre.</summary>
        protected global::System.Web.UI.WebControls.Literal litConfirmarCierre;

        /// <summary>Control btnCerrarACuenta.</summary>
        protected global::System.Web.UI.WebControls.Button btnCerrarACuenta;

        /// <summary>Control btnCerrarYCobrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnCerrarYCobrar;

        /// <summary>Control btnCancelarOrden.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarOrden;

        /// <summary>Control phCerrarOrden.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCerrarOrden;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
