//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class OrdenesDeTrabajo
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control ddlFiltroEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEstado;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control gvOrdenes.</summary>
        protected global::System.Web.UI.WebControls.GridView gvOrdenes;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdOrden;

        /// <summary>Control upnlCliente.</summary>
        protected global::System.Web.UI.UpdatePanel upnlCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litClienteSeleccionado;

        /// <summary>Control pnlSeleccionNueva.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSeleccionNueva;

        /// <summary>Control txtBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarCliente;

        /// <summary>Control btnBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarCliente;

        /// <summary>Control btnNuevoCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoCliente;

        /// <summary>Control pnlResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosCliente;

        /// <summary>Control rptResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosCliente;

        /// <summary>Control btnNuevoVehiculo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoVehiculo;

        /// <summary>Control ddlVehiculo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVehiculo;

        /// <summary>Control ddlTurno.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTurno;

        /// <summary>Control pnlSeleccionFija.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSeleccionFija;

        /// <summary>Control litVehiculoInfo.</summary>
        protected global::System.Web.UI.WebControls.Label litVehiculoInfo;

        /// <summary>Control litTurnoInfo.</summary>
        protected global::System.Web.UI.WebControls.Label litTurnoInfo;

        /// <summary>Control txtKilometraje.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtKilometraje;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control pnlEstado.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEstado;

        /// <summary>Control ddlEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>Control litEstadoActual.</summary>
        protected global::System.Web.UI.WebControls.Label litEstadoActual;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control btnCancelarOrden.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarOrden;

        /// <summary>Control pnlDetalle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        /// <summary>Control pnlAgregarServicio.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAgregarServicio;

        /// <summary>Control ddlServicio.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlServicio;

        /// <summary>Control txtCantidadServicio.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadServicio;

        /// <summary>Control btnAgregarServicio.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarServicio;

        /// <summary>Control gvServicios.</summary>
        protected global::System.Web.UI.WebControls.GridView gvServicios;

        /// <summary>Control pnlAgregarInsumo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAgregarInsumo;

        /// <summary>Control ddlInsumo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlInsumo;

        /// <summary>Control txtCantidadInsumo.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadInsumo;

        /// <summary>Control btnAgregarInsumo.</summary>
        protected global::System.Web.UI.WebControls.Button btnAgregarInsumo;

        /// <summary>Control gvInsumosOrden.</summary>
        protected global::System.Web.UI.WebControls.GridView gvInsumosOrden;
    }
}
