//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Pagos
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvPagos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvPagos;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control pnlVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeOrden;

        /// <summary>Control litVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Literal litVieneDeOrden;

        /// <summary>Control hdnIdVentaCobro.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdVentaCobro;

        /// <summary>Control upnlTitular.</summary>
        protected global::System.Web.UI.UpdatePanel upnlTitular;

        /// <summary>Control ddlTipo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;

        /// <summary>Control pnlCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCliente;

        /// <summary>Control txtCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control pnlProveedor.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlProveedor;

        /// <summary>Control txtProveedor.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtProveedor;

        /// <summary>Control hdnIdProveedor.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdProveedor;

        /// <summary>Control lblSaldoTitular.</summary>
        protected global::System.Web.UI.WebControls.Label lblSaldoTitular;

        /// <summary>Control ddlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMedioPago;

        /// <summary>Control txtMonto.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMonto;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control btnRegistrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
    }
}
