//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Pagos
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control gvPagos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvPagos;

        /// <summary>Control ddlTipo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;

        /// <summary>Control upnlTitular.</summary>
        protected global::System.Web.UI.UpdatePanel upnlTitular;

        /// <summary>Control pnlCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litClienteSeleccionado;

        /// <summary>Control txtBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarCliente;

        /// <summary>Control btnBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarCliente;

        /// <summary>Control pnlResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosCliente;

        /// <summary>Control rptResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosCliente;

        /// <summary>Control pnlProveedor.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlProveedor;

        /// <summary>Control hdnIdProveedor.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdProveedor;

        /// <summary>Control litProveedorSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litProveedorSeleccionado;

        /// <summary>Control txtBuscarProveedor.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarProveedor;

        /// <summary>Control btnBuscarProveedor.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarProveedor;

        /// <summary>Control pnlResultadosProveedor.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosProveedor;

        /// <summary>Control rptResultadosProveedor.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosProveedor;

        /// <summary>Control ddlComprobante.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlComprobante;

        /// <summary>Control ddlMedioPago.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMedioPago;

        /// <summary>Control txtMonto.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMonto;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control btnRegistrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
    }
}
