//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Proveedores
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control chkIncluirInactivos.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIncluirInactivos;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvProveedores.</summary>
        protected global::System.Web.UI.WebControls.GridView gvProveedores;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control hdnIdProveedor.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdProveedor;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control txtRazonSocial.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;

        /// <summary>Control txtCuit.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCuit;

        /// <summary>Control txtTelefono.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        /// <summary>Control txtEmail.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>Control txtDireccion.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;

        /// <summary>Control btnReactivar.</summary>
        protected global::System.Web.UI.WebControls.Button btnReactivar;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
