//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Registro
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control txtApellido.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>Control txtEmail.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>Control txtPassword.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>Control txtRepetir.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtRepetir;

        /// <summary>Control btnRegistrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
    }
}
