//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Roles
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvRoles.</summary>
        protected global::System.Web.UI.WebControls.GridView gvRoles;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control pnlAvisoRol.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAvisoRol;

        /// <summary>Control litAvisoRol.</summary>
        protected global::System.Web.UI.WebControls.Literal litAvisoRol;

        /// <summary>Control hdnIdNivel.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdNivel;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control pnlAccesosRapidos.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAccesosRapidos;

        /// <summary>Control rptPermisos.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPermisos;

        /// <summary>Control litBotonCerrar.</summary>
        protected global::System.Web.UI.WebControls.Literal litBotonCerrar;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
