//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class SiteMaster
    {
        /// <summary>
        /// Control phNavegacion.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNavegacion;

        /// <summary>
        /// Control litMenu.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMenu;

        /// <summary>
        /// Control litUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsuario;

        /// <summary>
        /// Control lnkCerrarSesion.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkCerrarSesion;

        /// <summary>
        /// Control MainContent.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
