//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Turnos
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvTurnos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvTurnos;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control hdnIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdTurno;

        /// <summary>Control upnlCliente.</summary>
        protected global::System.Web.UI.UpdatePanel upnlCliente;

        /// <summary>Control txtCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control ddlVehiculo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVehiculo;

        /// <summary>Control txtFecha.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFecha;

        /// <summary>Control txtHora.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtHora;

        /// <summary>Control ddlEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>Control litEstadoNuevo.</summary>
        protected global::System.Web.UI.WebControls.Label litEstadoNuevo;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
