//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Turnos
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control ddlFiltroEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEstado;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control gvTurnos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvTurnos;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdTurno;

        /// <summary>Control upnlCliente.</summary>
        protected global::System.Web.UI.UpdatePanel upnlCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litClienteSeleccionado;

        /// <summary>Control txtBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarCliente;

        /// <summary>Control btnBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarCliente;

        /// <summary>Control pnlResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosCliente;

        /// <summary>Control rptResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosCliente;

        /// <summary>Control ddlVehiculo.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVehiculo;

        /// <summary>Control txtFecha.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFecha;

        /// <summary>Control txtHora.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtHora;

        /// <summary>Control ddlEstado.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>Control txtObservaciones.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;
    }
}
