//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Usuarios
    {
        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdUsuario.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdUsuario;

        /// <summary>Control txtNombre.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Control txtApellido.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>Control txtEmail.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>Control ddlNivel.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        /// <summary>Control chkActivo.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActivo;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnCancelar.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>Control gvUsuarios.</summary>
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
    }
}
