//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Vehiculos
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control hdnVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeOrden;

        /// <summary>Control hdnOrKilometraje.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrKilometraje;

        /// <summary>Control hdnOrObservaciones.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrObservaciones;

        /// <summary>Control hdnOrIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrIdTurno;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control gvVehiculos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvVehiculos;

        /// <summary>Control pnlFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control pnlErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorFormulario;

        /// <summary>Control litErrorFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorFormulario;

        /// <summary>Control pnlVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeOrden;

        /// <summary>Control btnVolverAOrdenes.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAOrdenes;

        /// <summary>Control hdnIdVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdVehiculo;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control pnlDuenoSeleccion.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDuenoSeleccion;

        /// <summary>Control txtCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control btnNuevoCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoCliente;

        /// <summary>Control pnlDuenoFijo.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDuenoFijo;

        /// <summary>Control litDuenoActual.</summary>
        protected global::System.Web.UI.WebControls.Literal litDuenoActual;

        /// <summary>Control btnCambiarDueno.</summary>
        protected global::System.Web.UI.WebControls.Button btnCambiarDueno;

        /// <summary>Control txtPatente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPatente;

        /// <summary>Control txtAnio.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAnio;

        /// <summary>Control valAnio.</summary>
        protected global::System.Web.UI.WebControls.RangeValidator valAnio;

        /// <summary>Control txtMarca.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarca;

        /// <summary>Control txtModelo.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtModelo;

        /// <summary>Control ddlTipoCombustible.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCombustible;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;

        /// <summary>Control btnReactivar.</summary>
        protected global::System.Web.UI.WebControls.Button btnReactivar;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control pnlCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCambioDueno;

        /// <summary>Control litTituloCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloCambioDueno;

        /// <summary>Control pnlErrorCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlErrorCambioDueno;

        /// <summary>Control litErrorCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.Literal litErrorCambioDueno;

        /// <summary>Control hdnIdVehiculoDueno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdVehiculoDueno;

        /// <summary>Control litVehiculoCambio.</summary>
        protected global::System.Web.UI.WebControls.Literal litVehiculoCambio;

        /// <summary>Control litDuenoAnterior.</summary>
        protected global::System.Web.UI.WebControls.Literal litDuenoAnterior;

        /// <summary>Control txtNuevoDueno.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNuevoDueno;

        /// <summary>Control hdnIdNuevoDueno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdNuevoDueno;

        /// <summary>Control btnNuevoClienteDueno.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoClienteDueno;

        /// <summary>Control btnConfirmarCambioDueno.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarCambioDueno;
    }
}
