//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Vehiculos
    {
        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control hdnVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnVieneDeOrden;

        /// <summary>Control hdnOrKilometraje.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrKilometraje;

        /// <summary>Control hdnOrObservaciones.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrObservaciones;

        /// <summary>Control hdnOrIdTurno.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnOrIdTurno;

        /// <summary>Control pnlVieneDeOrden.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlVieneDeOrden;

        /// <summary>Control btnVolverAOrdenes.</summary>
        protected global::System.Web.UI.WebControls.Button btnVolverAOrdenes;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control btnNuevoCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoCliente;

        /// <summary>Control chkIncluirInactivos.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIncluirInactivos;

        /// <summary>Control gvVehiculos.</summary>
        protected global::System.Web.UI.WebControls.GridView gvVehiculos;

        /// <summary>Control litTituloFormulario.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloFormulario;

        /// <summary>Control hdnIdVehiculo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdVehiculo;

        /// <summary>Control hdnActivo.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnActivo;

        /// <summary>Control upnlCliente.</summary>
        protected global::System.Web.UI.UpdatePanel upnlCliente;

        /// <summary>Control hdnIdCliente.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIdCliente;

        /// <summary>Control litClienteSeleccionado.</summary>
        protected global::System.Web.UI.WebControls.Label litClienteSeleccionado;

        /// <summary>Control txtBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarCliente;

        /// <summary>Control btnBuscarCliente.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscarCliente;

        /// <summary>Control pnlResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResultadosCliente;

        /// <summary>Control rptResultadosCliente.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultadosCliente;

        /// <summary>Control txtPatente.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPatente;

        /// <summary>Control txtMarca.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarca;

        /// <summary>Control txtModelo.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtModelo;

        /// <summary>Control txtAnio.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAnio;

        /// <summary>Control ddlTipoCombustible.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCombustible;

        /// <summary>Control btnGuardar.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>Control btnNuevo.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>Control btnBorrar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBorrar;
    }
}
