//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026
{
    public partial class Ventas
    {
        /// <summary>Control pnlSoloLectura.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSoloLectura;

        /// <summary>Control pnlMensaje.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;

        /// <summary>Control litMensaje.</summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>Control txtBuscar.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control gvVentas.</summary>
        protected global::System.Web.UI.WebControls.GridView gvVentas;

        /// <summary>Control pnlDetalle.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        /// <summary>Control litTituloDetalle.</summary>
        protected global::System.Web.UI.WebControls.Literal litTituloDetalle;

        /// <summary>Control litClienteInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litClienteInfo;

        /// <summary>Control litVehiculoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litVehiculoInfo;

        /// <summary>Control litFechaInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litFechaInfo;

        /// <summary>Control litSubtotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSubtotalInfo;

        /// <summary>Control litImpuestosInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litImpuestosInfo;

        /// <summary>Control litTotalInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalInfo;

        /// <summary>Control litSaldoInfo.</summary>
        protected global::System.Web.UI.WebControls.Literal litSaldoInfo;

        /// <summary>Control gvDetalleVenta.</summary>
        protected global::System.Web.UI.WebControls.GridView gvDetalleVenta;
    }
}
