//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LubricentroControl_2026.Reportes
{
    public partial class VentasPorPeriodo
    {
    }
}